ratings = (5, 4, 5, 3, 4, 5, 2, 5)
print("Number of 5-star ratings:", ratings.count(5))
print("First 3-star rating index:", ratings.index(3))
print("Total Ratings:", len(ratings))
print("Highest Rating:", max(ratings))
print("Lowest Rating:", min(ratings))
print("Total Score:", sum(ratings))
print("Index of 2:", ratings.index(2))
print("4 -star ratings:", ratings.count(4))
print("Average Rating:", sum(ratings) / len(ratings)) 
